chore: mock info and debug which are used in capability.ts (#2331)
## Description

The build calls the Capability class which does a `Log.info` and
`Log.debug`. This mocks the logger in order to clean up our unit tests
and suppresses frivolous warnings about the `punycode` deprecation


```ts
 FAIL  src/cli/build.test.ts > handleValidCapabilityNames > should call validateCapabilityNames with capabilities
TypeError: default.debug is not a function
 ❯ new Capability src/lib/core/capability.ts:137:9
    135| 
    136|     Log.info(`Capability ${this.#name} registered`);
    137|     Log.debug(cfg);
       |         ^
    138|   }
    139| 
```

End to End Test:  <!-- if applicable -->  
(See [Pepr Excellent
Examples](https://github.com/defenseunicorns/pepr-excellent-examples))

## Related Issue

Fixes #2294 
<!-- or -->
Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging
- [ ] Unit,
[Journey](https://github.com/defenseunicorns/pepr/tree/main/journey),
[E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples),
[docs](https://github.com/defenseunicorns/pepr/tree/main/docs),
[adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or
updated as needed
- [ ] [Contributor Guide
Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request)
followed

---------

Signed-off-by: Case Wylie <cmwylie19@defenseunicorns.com>