test: make load test err msg explicit (#1478)
## Description

Overnight load test failed just as it was beginning -- 2.5 min into a 3
hr expected runtime. Diagnosing failure let to discovery of an unhelpful
message: `The promise rejected with the reason "#<Object>".`

This PR adds the catch block necessary to see what actually went wrong.


```
Load test start: 2024-11-22T05:09:47.892Z
{
  "module": "/home/runner/work/pepr/pepr/pepr-excellent-examples/hello-pepr-load",
  "manifest": "/home/runner/work/pepr/pepr/pepr-excellent-examples/hello-pepr-load/capabilities/configmap.yaml"
}
{
  "actInterval": "1m",
  "actIntensity": 4000,
  "audInterval": "1s",
  "clusterName": "pepr-load-cluster",
  "duration": "1h",
  "outputDir": "/home/runner/work/pepr/pepr/pepr/load",
  "settle": "2h",
  "stagger": "5s"
}

UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".
    at throwUnhandledRejectionsMode (node:internal/process/promises:389:7)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:[32](https://github.com/defenseunicorns/pepr/actions/runs/11966824488/job/33363083364#step:16:33)) {
  code: 'ERR_UNHANDLED_REJECTION'
}
↓
Error: Process completed with exit code 1.
```

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging
- [ ] Unit,
[Journey](https://github.com/defenseunicorns/pepr/tree/main/journey),
[E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples),
[docs](https://github.com/defenseunicorns/pepr/tree/main/docs),
[adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or
updated as needed
- [ ] [Contributor Guide
Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request)
followed